#!/usr/bin/env node
/**
 * Generates test/visual/fixture.html — one card per registry class, with the
 * correct host element and required children/char spans, driven entirely by
 * registry/motion.registry.json (R3). The Playwright visual suite and the
 * perf suite both consume this page.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..", "..");
const registry = JSON.parse(fs.readFileSync(path.join(ROOT, "registry", "motion.registry.json"), "utf8"));

const effects = registry.classes.filter((c) => c.kind === "effect");

function hostFor(c) {
  switch (c.category) {
    case "buttons": return { tag: "button", text: "Button" };
    case "inputs": return c.inputWrap
      ? { tag: "wrap-input", withLabel: (c.selectors || []).some((s) => /\blabel\b/.test(s)) }
      : { tag: "input", text: null };
    case "loaders": return { tag: "span", text: c.name === "sds-loader-type" ? "load" : null };
    case "cards": return { tag: "div", text: "Card", card: true };
    case "scroll": return { tag: "div", text: "Scroll" };
    default: return { tag: "span", text: "Motion" };
  }
}

function childrenMarkup(c) {
  if (c.requiresCharSplit) {
    return "SDS".split("").map((ch, i) =>
      `<span class="sds-char" style="display:inline-block;--i:${i}">${ch}</span>`).join("");
  }
  if (c.requiresChildren) {
    if (c.category === "buttons") return "<span>→</span><span>Go</span>";
    const n = /grid|mosaic/.test(c.name) ? 9 : /ping/.test(c.name) ? 1 : 4;
    const childText = ["cards", "scroll", "text"].includes(c.category) ? "It" : "";
    return Array.from({ length: n }, () => `<span>${childText}</span>`).join("");
  }
  return null;
}

const cards = effects.map((c) => {
  const host = hostFor(c);
  let el;
  const kids = childrenMarkup(c);
  if (host.tag === "wrap-input") {
    el = host.withLabel
      ? `<div class="${c.name}" id="el-${c.name}"><input placeholder=" " /><label>Label</label></div>`
      : `<div class="${c.name}" id="el-${c.name}"><input placeholder="Type here" /></div>`;
  } else if (host.tag === "input") {
    el = `<input class="${c.name}" id="el-${c.name}" value="Input" />`;
  } else {
    const content = kids ?? host.text ?? "";
    const style = host.card ? ' style="width:140px;height:80px;background:#eef;border-radius:10px;display:flex;align-items:center;justify-content:center;"' : "";
    el = `<${host.tag} class="${c.name}" id="el-${c.name}"${style}>${content}</${host.tag}>`;
  }
  return `<div class="cell" id="cell-${c.name}" data-effect="${c.name}" data-category="${c.category}">${el}</div>`;
});

const html = `<!doctype html>
<!-- GENERATED by scripts/visual/generate-fixture.js from the motion registry — do not edit. -->
<html lang="en">
<head>
<meta charset="utf-8" />
<title>SDS Motion Forge — visual fixture (${effects.length} effects)</title>
<link rel="stylesheet" href="/dist/motion.css" />
<style>
  /* Deterministic environment: web-safe font, fixed cell geometry, no
     external resources, no scrollbars inside cells. */
  * { box-sizing: border-box; }
  body { margin: 0; font-family: Arial, Helvetica, sans-serif; background: #ffffff; }
  .cell {
    width: 220px; height: 120px; overflow: hidden; background: #ffffff;
    display: flex; align-items: center; justify-content: center;
    font-size: 20px; color: #10131c; contain: strict;
  }
  .cell input { width: 170px; padding: 8px 10px; border: 1px solid #aab; border-radius: 8px; font: inherit; }
  .cell button { padding: 10px 18px; border: 1px solid #aab; border-radius: 8px; background: #2233dd; color: #fff; font: inherit; }
</style>
</head>
<body>
${cards.join("\n")}
</body>
</html>
`;

const out = path.join(ROOT, "test", "visual", "fixture.html");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, html);
console.log(`fixture: ${effects.length} effects -> test/visual/fixture.html`);
